#!/usr/bin/env ruby

require 'dishiz'
require 'yaml'

include Dishiz
exe = Executable.new

puts NetStateDisplayer.new(exe.network).display_keys

time_limit = TimeExpr.new(ARGV[1] || '10ns').ps

# initial
ss = SimStep.new(exe.network)
#puts ss.simstate
ss.calc!
puts ss.simstate

loop do
  break if ss.futurelist.length.zero?

  ss2 = SimStep.new(exe.network, ss)
  break if ss2.time > time_limit
  #puts ss2.simstate
  ss2.calc!
  puts ss2.simstate

  ss = ss2
end

   #puts ss2.futurelist.map{|k,v| [k,v.to_a]}.to_h.to_yaml
